lang = "en"
host = "kitchen.tmpfs.org"

[dependencies]
"std::core" = { version = "~3" }
"std::crumbtrail" = { version = "~1", apply = { styles = [ "/**/**" ] } }

[build]
rewrite-index = true

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[page]
description = "Some recipes"
keywords = "Kitchen, Food, Cooking"
authors = ["tmpfs"]

[pages."index.md"]
title = "Home"

[pages."404.html"]
standalone = true
rewrite-index = false
