lang = "en"
host = "kitchen.tmpfs.org"

[dependencies]
"std::core" = { version = "~1" }

[styles]
main = ["/assets/css/style.css"]

[build]
rewrite-index = true

[page]
description = "Some recipes"
keywords = "Kitchen, Food, Cooking"
authors = [{ name = "Muji", url = "https://tmpfs.org" }]

[pages."index.md"]
title = "Home"

[pages."404.html"]
standalone = true
rewrite-index = false
