lang = "en"
host = "recipes.tmpfs.org"

[build]
rewrite-index = true

[page]
description = "Some recipes"
keywords = "Kitchen, Food, Cooking"
authors = [{ name = "muji", url = "https://tmpfs.org" }]

[pages."index.md"]
title = "Home"

[pages."404.html"]
standalone = true
rewrite-index = false
