[package]
name = "rust-fsm-model"
version = "0.1.0"
authors = ["muji <muji@tmpfs.org>"]
edition = "2018"

[dependencies]
async-trait = "^0.1"
log = "^0.4"
pretty_env_logger = "^0.4"
tokio = {version = "^1.8", features = ["full"] }
