lang = "en"
host = "blog.tmpfs.org"

[dependencies]
"std::author" = "^1"
"std::feed" = "^2"
"std::syntax" = "^1"

[dependencies."std::core"]
version = "^5"

[dependencies."std::core".apply]
styles = ["**"]

[dependencies."std::blueprint::blog"]
version = "1.0.7"

[page]
description = "Blog"
keywords = "Weblog, News, Articles"
authors = ["tmpfs"]

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[feed.posts]
title = "Muji's Blog"
description = "Tech stuff"
favicon = "/favicon.ico"
target = "posts"
includes = ["/posts/**"]
excludes = ["/posts/[0-9]*/", "/posts/"]

[feed.posts.alternate]
includes = ["/", "/posts/**/*.html"]

[syntax]
theme = "Solarized (light)"

[transform.html]
strip-comments = true
toc = true
words = true

[db.load.posts]
type = "toml"
provider = "pages"
from = "posts"
excludes = ["index.*"]

[db.load.posts.on.all]
key = "*"

[db.load.posts.on.tags]
key = "taxonomies.tags"

[redirects]
"/posts/" = "/posts/1/"

[pages."index.md".query]
name = "posts"
index = "all"
include-docs = true
sort = "created"
desc = true
limit = 2

[pages."posts/index.md".query]
name = "posts"
index = "all"
include-docs = true
sort = "created"
desc = true
page = { size = 2 }

[pages."tags/index.md".query]
name = "posts"
index = "tags"
include-docs = true

[pages."tags/index.md".query.group]
path = "taxonomies.tags"
expand = true

[pages."tags/item.md"]
title = "Tag"

[pages."tags/item.md".query]
name = "posts"
index = "tags"
each = true
include-docs = true

[pages."tags/item.md".query.group]
path = "taxonomies.tags"
expand = true
