lang = "en"
host = "tmpfs.org"

[publish.aws.stage]
credentials-profile = "tmpfs"
path = "stage"

[publish.aws.production]
credentials-profile = "tmpfs"
path = "production"

[build]
source = "site"
target = "build"

[page]
description = "Experienced digital craftsman and teacher"
keywords = "Digital, Software, Consultant, Rust, Kotlin, Java, Website, Server, Cloud, Web Developer, Full Stack, HTML, Javascript, CSS"
author = { name = "muji", url = "https://tmpfs.org" }

