lang = "en"
host = "tmpfs.org"

[dependencies]
"std::core" = { version = "~3" }

[build]
rewrite-index = true
extend = ["html"]

[authors.tmpfs]
name = "Muji"
url = "https://tmpfs.org"

[page]
description = "Experienced digital craftsman and teacher"
keywords = "Digital, Software, Consultant, Rust, Kotlin, Java, Website, Server, Cloud, Web Developer, Full Stack, HTML, Javascript, CSS"
authors = ["tmpfs"]

[pages."index.html"]
title = "Home"

[pages."google17a6906a04e2c5e4.html"]
standalone = true
rewrite-index = false

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"

[publish.aws.environments.stage]
bucket = "stage.tmpfs.org"

[publish.aws.environments.production]
bucket = "tmpfs.org"
