lang = "en"
host = "tmpfs.org"

[build]
source = "site"
target = "build"

[page]
description = "Experienced digital craftsman and teacher"
keywords = "Digital, Software, Consultant, Rust, Kotlin, Java, Website, Server, Cloud, Web Developer, Full Stack, HTML, Javascript, CSS"
author = { name = "muji", url = "https://tmpfs.org" }

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"
environments = {stage = {prefix = "stage"}, production = {prefix = "production"}}

